/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Batalla.java
 *
 * Created on 23-feb-2015, 13:51:17
 */
package sistemadebatalla;
import java.applet.AudioClip;
import javax.swing.JOptionPane;
import java.awt.event.*;

/**
 *
 * @author Alderf-Bandai
 */
public class Batalla extends javax.swing.JFrame {

    /** Creates new form Batalla */
    public Batalla() {
        initComponents();
        setLocationRelativeTo(null);
        //setSize(500,500);
        int vidach2 = hp_6.getValue();
         hp_6.setMaximum(2000);
        hp_6.setValue(2000);
        hp_1.setMaximum(1000);
        hp_1.setValue(1000);
        hp_2.setMaximum(800);
        hp_2.setValue(800);
        hp_3.setMaximum(700);
        hp_3.setValue(700);
        vida2.setText(""+vidach2);
        int vidach = hp_1.getValue();
        vida2.setText(""+vidach);
        
       fondoo f = new fondoo();
        f.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hp_1 = new javax.swing.JProgressBar();
        boton = new javax.swing.JButton();
        attack = new javax.swing.JButton();
        special = new javax.swing.JButton();
        special1 = new javax.swing.JButton();
        attack1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        atkM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hp_6 = new javax.swing.JProgressBar();
        vida2 = new javax.swing.JTextField();
        vida = new javax.swing.JTextField();
        panelpalkia = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        hp_2 = new javax.swing.JProgressBar();
        attack2 = new javax.swing.JButton();
        special2 = new javax.swing.JButton();
        panelpalkia1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        hp_3 = new javax.swing.JProgressBar();
        attack3 = new javax.swing.JButton();
        special3 = new javax.swing.JButton();
        panelpalkia2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hp_1.setForeground(new java.awt.Color(50, 251, 9));
        hp_1.setMaximum(0);
        hp_1.setToolTipText("");
        hp_1.setStringPainted(true);
        getContentPane().add(hp_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 150, -1));

        boton.setText("Salir");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        attack.setText("Ataque Super Mega Way Final Flash");
        attack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attackMouseClicked(evt);
            }
        });
        attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackActionPerformed(evt);
            }
        });
        getContentPane().add(attack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, -1));

        special.setText("Special attack Sukistrukis");
        special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialActionPerformed(evt);
            }
        });
        getContentPane().add(special, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, -1));

        special1.setText("Recuperacion");
        special1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special1ActionPerformed(evt);
            }
        });
        getContentPane().add(special1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 100, -1));

        attack1.setText("Super ataque");
        attack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack1ActionPerformed(evt);
            }
        });
        getContentPane().add(attack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, -1));

        jLabel8.setText("Atk:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        atkM.setText("25");
        getContentPane().add(atkM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadebatalla/487.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        hp_6.setForeground(new java.awt.Color(50, 251, 9));
        hp_6.setMaximum(0);
        hp_6.setToolTipText("");
        hp_6.setStringPainted(true);
        getContentPane().add(hp_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 150, -1));
        getContentPane().add(vida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 70, -1));
        getContentPane().add(vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 70, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadebatalla/484.gif"))); // NOI18N
        panelpalkia.add(jLabel7);

        getContentPane().add(panelpalkia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 110));

        hp_2.setForeground(new java.awt.Color(50, 251, 9));
        hp_2.setMaximum(0);
        hp_2.setToolTipText("");
        hp_2.setStringPainted(true);
        getContentPane().add(hp_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        attack2.setText("Ataque Super Mega Way Final Flash");
        attack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attack2MouseClicked(evt);
            }
        });
        attack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack2ActionPerformed(evt);
            }
        });
        getContentPane().add(attack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, -1));

        special2.setText("Special attack Sukistrukis");
        special2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special2ActionPerformed(evt);
            }
        });
        getContentPane().add(special2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadebatalla/384.gif"))); // NOI18N
        panelpalkia1.add(jLabel9);

        getContentPane().add(panelpalkia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, 110));

        hp_3.setForeground(new java.awt.Color(50, 251, 9));
        hp_3.setMaximum(0);
        hp_3.setToolTipText("");
        hp_3.setStringPainted(true);
        getContentPane().add(hp_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, -1));

        attack3.setText("Ataque Super Mega Way Final Flash");
        attack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attack3MouseClicked(evt);
            }
        });
        attack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack3ActionPerformed(evt);
            }
        });
        getContentPane().add(attack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, -1));

        special3.setText("Special attack Sukistrukis");
        special3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special3ActionPerformed(evt);
            }
        });
        getContentPane().add(special3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 90, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadebatalla/483.gif"))); // NOI18N
        panelpalkia2.add(jLabel10);

        getContentPane().add(panelpalkia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 110));

        pack();
    }// </editor-fold>

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {                                      
    int desicion = JOptionPane.showConfirmDialog(this,"Seguro que desea salir, podria perder la partida? ","Confirmar.",JOptionPane.OK_CANCEL_OPTION);
 
if(desicion == JOptionPane.OK_CANCEL_OPTION){
 
}else{
    this.dispose(); }
    
    }                                     

    private void attackActionPerformed(java.awt.event.ActionEvent evt) {                                       
      int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 99, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_6.setValue(0);
       hp_6.setValue(dañorev);
        
        }
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
}        
    }                                      

    private void attack1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
       int vidach2 = hp_1.getValue();
       int vidach3 = hp_2.getValue();
       int vidach4 = hp_3.getValue();
vida.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 199, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_1.setValue(0);
       hp_1.setValue(dañorev);
        
        }else{
       if(contador<vidach3){
        dañorev = contador-damage;
        hp_2.setValue(0);
       hp_2.setValue(dañorev);
        
        }else{
       if(contador<vidach4){
        dañorev = contador-damage;
        hp_3.setValue(0);
       hp_3.setValue(dañorev);
        
        }else{
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
       }
       }
       }
       
} 
    }                                       

    private void attackMouseClicked(java.awt.event.MouseEvent evt) {                                    
    
     
     
     
    }                                   

    private void attack2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void attack2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
   int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 99, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_6.setValue(0);
       hp_6.setValue(dañorev);
        
        }
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
}          // TODO add your handling code here:
    }                                       

    private void attack3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void attack3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
   int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 99, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_6.setValue(0);
       hp_6.setValue(dañorev);
        
        }
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
}          // TODO add your handling code here:
    }                                       

    private void special1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int salud = 240, ttt=0;
        
       if(contador<vidach2){
        ttt = contador+salud;
        hp_6.setValue(0);
       hp_6.setValue(ttt);
        
        }
      
}  
    }                                        

    private void specialActionPerformed(java.awt.event.ActionEvent evt) {
      int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 150, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_6.setValue(0);
       hp_6.setValue(dañorev);
        
        }
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
}  
    }

    private void special2ActionPerformed(java.awt.event.ActionEvent evt) {
       int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 130, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_6.setValue(0);
       hp_6.setValue(dañorev);
        
        }
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
}  
    }

    private void special3ActionPerformed(java.awt.event.ActionEvent evt) {
       int vidach2 = hp_6.getValue();
vida2.setText(""+vidach2);

for(int contador = 0; contador <= vidach2; contador++ ){
    int damage = 200, dañorev=0;
        
       if(contador<vidach2){
        dañorev = contador-damage;
        hp_6.setValue(0);
       hp_6.setValue(dañorev);
        
        }
       if(vidach2<=0){
           JOptionPane.showMessageDialog(null,"fELICIADAES HA GANADO");
       }
}  
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Batalla().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JLabel atkM;
    private javax.swing.JButton attack;
    private javax.swing.JButton attack1;
    private javax.swing.JButton attack2;
    private javax.swing.JButton attack3;
    private javax.swing.JButton boton;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JProgressBar hp_1;
    public static javax.swing.JProgressBar hp_2;
    public static javax.swing.JProgressBar hp_3;
    public static javax.swing.JProgressBar hp_6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelpalkia;
    private javax.swing.JPanel panelpalkia1;
    private javax.swing.JPanel panelpalkia2;
    private javax.swing.JButton special;
    private javax.swing.JButton special1;
    private javax.swing.JButton special2;
    private javax.swing.JButton special3;
    private javax.swing.JTextField vida;
    private javax.swing.JTextField vida2;
    // End of variables declaration

    
    
    
    
   
    

}



