/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectChar.java
 *
 * Created on 23-feb-2015, 10:14:52
 */
package sistemadebatalla;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Alderf-Bandai
 */


public class SelectChar extends javax.swing.JFrame {
    
    //public static int personaje1 =1000;

    /** Creates new form SelectChar */
    public SelectChar() {
        initComponents();
        // setLocationRelativeTo(null);
         iniciar();
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        p1 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        personaje1 = new javax.swing.JTextField();
        personaje2 = new javax.swing.JTextField();
        cuadper1 = new javax.swing.JTextField();
        comboper1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p1MousePressed(evt);
            }
        });
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 130));

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 130));

        jLabel1.setText("Seleccion de Personaje");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(personaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, -1));
        getContentPane().add(personaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, -1));

        cuadper1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadper1ActionPerformed(evt);
            }
        });
        getContentPane().add(cuadper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, -1));

        comboper1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "personaje1", "personaje2", "personaje3", "personaje4", "personaje5", "personaje6" }));
        getContentPane().add(comboper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 20));

        jButton3.setText("LET'S GO!");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 70));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
int desicion = JOptionPane.showConfirmDialog(this,"Seguro que desea salir?","Confirmar.",JOptionPane.OK_CANCEL_OPTION);
 if(desicion == JOptionPane.OK_CANCEL_OPTION){
}else{this.dispose();
 }
    }//GEN-LAST:event_salirActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
rediBatalla();   
int valor = Batalla.hp_1.getValue();
//if(valor){
Batalla.hp_1.setMaximum(1000);
Batalla.hp_1.setValue(1000);
int attack = 85, special = 125;
          
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed


    }//GEN-LAST:event_p2ActionPerformed

    private void p1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MousePressed
       
    }//GEN-LAST:event_p1MousePressed

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_p1MouseClicked

    private void cuadper1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadper1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadper1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
per1();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  rediBatalla();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SelectChar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboper1;
    private javax.swing.JTextField cuadper1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton p1;
    private javax.swing.JButton p2;
    private javax.swing.JTextField personaje1;
    private javax.swing.JTextField personaje2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
 
    
    
private void rediBatalla(){
Batalla a = new Batalla();
a.setLocationRelativeTo(null);
a.setVisible(true);
}

private void iniciar(){
this.setVisible(true);
this.setSize(597 , 408);    
}
      

private void per1 (){

    if (comboper1.getSelectedIndex() == -1) { 
 JOptionPane.showMessageDialog(null,"Debe seleccionar al menos un Moob\n");
} else { 
switch (comboper1.getSelectedIndex()) {
case 0: 
JOptionPane.showMessageDialog(null,"Al menos seleccione un personaje.");

     break;
case 1: 
//JOptionPane.showMessageDialog(null,"Selecciono a charizard\n despues solo hay que mandar lo eVs al form batalla");
rediBatalla();
Batalla.hp_1.setMaximum(900);
Batalla.hp_1.setValue(900);
int attack = 85, special = 125;
 


     break;

case 2: 
  //JOptionPane.showMessageDialog(null,"Selecciono a gengar\n");
    rediBatalla();
    Batalla.hp_1.setMaximum(700);
    Batalla.hp_1.setValue(700);
   int attack1 = 125, special1 = 140;
    

     break;
    case 3: 
  //JOptionPane.showMessageDialog(null,"Selecciono a gengar\n");
   rediBatalla(); 
    Batalla.hp_1.setMaximum(700);
    Batalla.hp_1.setValue(700);
   int attack2 = 125, special2 = 140;
    
     break;
        
        case 4: 
  //JOptionPane.showMessageDialog(null,"Selecciono a gengar\n");
   rediBatalla(); 
    Batalla.hp_1.setMaximum(700);
    Batalla.hp_1.setValue(700);
   int attack3 = 125, special3 = 140;
    
     break;
            case 5: 
  //JOptionPane.showMessageDialog(null,"Selecciono a gengar\n");
   rediBatalla(); 
    Batalla.hp_1.setMaximum(700);
    Batalla.hp_1.setValue(700);
   int attack4 = 125, special4 = 140;
    
     break;
 }


} 

}    
     


}
    
    

     
